baseurl                  = "https://lancatlin.github.io/holidays-weekend"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Holiday's Weekend"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006 01/02"
    dateformfull         = "2006 01/02 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link
    footerText           = "Miko Guitar 米可吉他"
    overlay = "#272932" # optional

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["./bg.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Holiday's Weekend"
    # rss                = ""

[[params.mainMenu]]
    link = "songs"
    text = "曲目"

[[params.mainMenu]]
    link = "artists"
    text = "演出者"

[[params.mainMenu]]
    link = "portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "about"
    text = "關於"

[imaging]
    quality = 0
