baseurl                  = "https://lancatlin.github.io/holidays-weekend"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Holiday's Weekend"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006 01/02"
    dateformfull         = "2006 01/02 15:04:05 EST"
    favicon              = "guitar.svg"
    homepage             = "首頁"                           # What to call the home page link
    footerText           = "[Miko Guitar 米可吉他](https://mikoguitar.com.tw/)"
    overlay = "#272932" # optional

# Metadata for Open Graph and Twitter
    description          = "Holiday's Weekend"               # Max 160 characters show in search results
    images               = ["./bg.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Holiday's Weekend"
    # rss                = ""

[[params.mainMenu]]
    link = "concert-program"
    text = "曲目"

[[params.mainMenu]]
    link = "performers"
    text = "演出者"

[[params.mainMenu]]
    link = "about"
    text = "團體簡介"

[[params.mainMenu]]
    link = "https://forms.gle/74rBJGWA73wDsxoS6"
    text = "回饋問卷"

[imaging]
    quality = 0
